# Realsense 435i setting

#==============#
# Camera Model #
#==============#

Camera.name: "Realsense 435i"
Camera.setup: "monocular"
Camera.model: "fisheye"
# perspective

Camera.fx: 608.958435
Camera.fy: 608.723389
Camera.cx: 321.793488
Camera.cy: 240.326843

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0
Camera.k4: 0.0

Camera.fps: 30.0
Camera.cols: 640
Camera.rows: 480

Camera.color_order: "RGB"

#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 2000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7

#========================#
# Initializer Parameters #
#========================#

Initializer.scaling_factor: 5.0

